root: true
extends:
  - "eslint:recommended"
  - "airbnb-base"
  - "prettier"
env:
  es2021: true
parserOptions:
  ecmaVersion: 2021
rules:
  no-console: off
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
