# Prettier
# cf. https://prettier.io

printWidth = 140        # default=80
tabWidth = 4            # default=2
arrowParens = "avoid"   # default="always"

[[overrides]]
files = ["*.json", "*.md", "*.yaml", "*.toml"]
options.tabWidth = 2