# cf.
# https://prettier.io/docs/en/options.html

printWidth = 140 # default=80
tabWidth = 4     # default=2

##### 実験用 #####

insertPragma = true
endOfLine = "lf" #git関連と併せて確認する必要あり
embeddedLanguageFormatting = "auto"

[[overrides]]
files = ["*.json", "*.md"]
options.tabWidth = 2
