# Prettier
# cf. https://prettier.io

printWidth = 140      # default=80
tabWidth = 4          # default=2
requirePragma = true  # default=false

[[overrides]]
files = ["*.json", "*.md"]
options.tabWidth = 2
